apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-with-pvc
spec:
  template:
    spec:
      containers:
      - name: write-data
        image: busybox
        volumeMounts:
        - name: data-storage
          mountPath: /data
        command: ["sh", "-c", "echo 'Job data' > /data/job-output.txt"]
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: job-pvc
      restartPolicy: Never