apiVersion: v1
kind: Secret
metadata:
  name: job-secret
type: Opaque
data:
  PASSWORD: c2VjdXJlcGFzc3dvcmQ= # Base64 encoded "securepassword"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-with-secret
spec:
  template:
    spec:
      containers:
      - name: print-secret
        image: busybox
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: job-secret
              key: PASSWORD
        command: ["sh", "-c", "echo $PASSWORD"]
      restartPolicy: Never