apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job
spec:
  parallelism: 3
  completions: 3
  template:
    spec:
      containers:
      - name: parallel-task
        image: busybox
        command: ["sh", "-c", "echo 'Running task' && sleep 5"]
      restartPolicy: Never