apiVersion: v1
kind: Pod
metadata:
  name: nginx-and-busybox
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: busybox
    image: busybox
    command: ["echo", "Hello from BusyBox"]