apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-and-config-reader
  namespace: backend-namespace
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-and-config-reader-sa
  namespace: backend-namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-and-config-reader-binding
  namespace: backend-namespace
subjects:
  - kind: ServiceAccount
    name: pod-and-config-reader-sa
    namespace: backend-namespace
roleRef:
  kind: Role
  name: pod-and-config-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-reader-deployment
  namespace: backend-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-reader
  template:
    metadata:
      labels:
        app: pod-reader
    spec:
      serviceAccountName: pod-and-config-reader-sa
      containers:
        - name: nginx
          image: nginx:1.23.3