apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-operator
  namespace: storage-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: storage-namespace
  name: pvc-operator
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "delete", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: storage-namespace
  name: bind-pvc-operator
subjects:
  - kind: ServiceAccount
    name: storage-operator
    namespace: storage-namespace
roleRef:
  kind: Role
  name: pvc-operator
  apiGroup: rbac.authorization.k8s.io
