apiVersion: v1
kind: Namespace
metadata:
  name: backend-namespace
  labels:
    environment: production
    team: backend
  annotations:
    description: "Namespace for backend services"
    owner: "team-backend@example.com"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: backend-namespace
  name: pod-reader
  labels:
    role-type: reader
    application: backend-app
  annotations:
    description: "Role to provide read and write access to pods and related resources"
    created-by: "admin@example.com"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]