apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: backend-namespace
subjects:
- kind: User
  name: "team-member@example.com"
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: backend-service-account
  namespace: backend-namespace
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
