apiVersion: v1
kind: Namespace
metadata:
  name: custom-namespace
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: custom-namespace
spec:
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service
  namespace: custom-namespace
subsets:
  - addresses:
      - ip: "10.0.0.1"
    ports:
      - port: 8080