apiVersion: v1
kind: Namespace
metadata:
  name: limit-range-ns

---
apiVersion: v1
kind: LimitRange
metadata:
  name: example-limitrange
  namespace: limit-range-ns
spec:
  limits:
  - max:
      cpu: "500m"
      memory: "1Gi"
    min:
      cpu: "100m"
      memory: "256Mi"
    default:
      cpu: "250m"
      memory: "512Mi"
    defaultRequest:
      cpu: "200m"
      memory: "400Mi"
    type: Container
