apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  app_name: MyApp
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  db_password: cGFzc3dvcmQ=  # Base64("password")