apiVersion: v1
kind: ConfigMap
metadata:
  name: app-deployment-config
data:
  log_level: info
  max_connections: "100"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: app-container
        image: nginx
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-deployment-config
              key: log_level
        - name: MAX_CONNECTIONS
          valueFrom:
            configMapKeyRef:
              name: app-deployment-config
              key: max_connections