apiVersion: v1
kind: ConfigMap
metadata:
  name: cronjob-config
  namespace: default
data:
  log_level: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: cronjob-secret
  namespace: default
type: Opaque
data:
  api_key: YXBpX2tleV9mb3JfYXBpX3N0cmluZw== # "api_key_for_api_string" (base64)
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
  namespace: default
spec:
  schedule: "*/1 * * * *"  # Run every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-container
              image: busybox
              command: ["sh", "-c", "env; echo 'Log Level: $LOG_LEVEL'; echo 'API Key: $API_KEY'"]
              env:
                - name: LOG_LEVEL
                  valueFrom:
                    configMapKeyRef:
                      name: cronjob-config
                      key: log_level
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: cronjob-secret
                      key: api_key
          restartPolicy: OnFailure