apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-storage
  labels:
    type: local
    environment: staging
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data